language: generic
os: linux
dist: xenial

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sourceline: "ppa:ubuntu-toolchain-r/test"
          packages: ['g++-7', 'cmake', 'libgtest-dev']
      env:
        - CC=gcc-7
        - CXX=g++-7

    - compiler: gcc
      addons:
        apt:
          sourceline: "ppa:ubuntu-toolchain-r/test"
          packages: ['g++-8', 'cmake', 'libgtest-dev']
      env:
        - CC=gcc-8
        - CXX=g++-8

    - compiler: gcc
      addons:
        apt:
          sourceline: "ppa:ubuntu-toolchain-r/test"
          packages: ['g++-9', 'cmake', 'libgtest-dev']
      env:
        - CC=gcc-9
        - CXX=g++-9

    - compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-xenial-6']
          sourceline: "ppa:ubuntu-toolchain-r/test"
          packages: ['clang-6.0', 'g++-7', 'cmake', 'libgtest-dev']
      env:
        - CC=clang-6.0
        - CXX=clang++-6.0

    - compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-xenial-7']
          sourceline: "ppa:ubuntu-toolchain-r/test"
          packages: ['clang-7', 'g++-7', 'cmake', 'libgtest-dev']
      env:
        - CC=clang-7
        - CXX=clang++-7

    - compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-xenial-8']
          sourceline: "ppa:ubuntu-toolchain-r/test"
          packages: ['clang-8', 'g++-8', 'cmake', 'libgtest-dev']
      env:
        - CC=clang-8
        - CXX=clang++-8

    - compiler: clang
      addons:
        apt:
          sources:
              sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main ppa:ubuntu-toolchain-r/test'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages: ['clang-9', 'g++-9', 'cmake', 'libgtest-dev']
      env:
        - CC=clang-9
        - CXX=clang++-9

script:
  - $CXX --version
  - ./configure
  - ./build/bin/MLogTest