dist: bionic
sudo: required
language: generic

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - cmake
            - libgtest-dev
        env:
          - C=gcc-7
          - CXX=g++-7

  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
            - cmake
            - libgtest-dev
        env:
          - C=gcc-8
          - CXX=g++-8

  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - g++-9
            - cmake
            - libgtest-dev
        env:
          - C=gcc-9
          - CXX=g++-9

  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-6
            - clang++-6
            - cmake
            - libgtest-dev
        env:
          - C=clang-61
          - CXX=clang++-6

  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-7
            - clang++-7
            - cmake
            - libgtest-dev
        env:
          - C=clang-7
          - CXX=clang++-7

  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-8
            - clang++-8
            - cmake
            - libgtest-dev
        env:
          - C=clang-8
          - CXX=clang++-8

  script:
    # Build the system
    - $C --version && $CXX --version && cmake --version
    - ./configure
    - ./build/bin/MLogTest