language: generic
os: linux
dist: bionic

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources: 
            - "ppa:ubuntu-toolchain-r/test"
            - sourceline: "ppa:george-edison55/cmake-3.x"
          packages: ['g++-7']
      env:
        - CC=gcc-7
        - CXX=g++-7

    - compiler: gcc
      addons:
        apt:
          sources: "ppa:ubuntu-toolchain-r/test"
          packages: ['g++-8', 'cmake']
      env:
        - CC=gcc-8
        - CXX=g++-8

    # TODO
    # - compiler: clang
    #   addons:
    #     apt:
    #       sources: ['llvm-toolchain-xenial-6']
    #       sourceline: "ppa:ubuntu-toolchain-r/test"
    #       packages: ['clang-6.0', 'g++-7', 'cmake']
    #   env:
    #     - CC=clang-6.0
    #     - CXX=clang++-6.0

    # - compiler: clang
    #   addons:
    #     apt:
    #       sources: ['llvm-toolchain-xenial-7']
    #       sourceline: "ppa:ubuntu-toolchain-r/test"
    #       packages: ['clang-7', 'g++-7', 'cmake']
    #   env:
    #     - CC=clang-7
    #     - CXX=clang++-7

    # - compiler: clang
    #   addons:
    #     apt:
    #       sources: ['llvm-toolchain-xenial-8']
    #       sourceline: "ppa:ubuntu-toolchain-r/test"
    #       packages: ['clang-8', 'g++-8', 'cmake']
    #   env:
    #     - CC=clang-8
    #     - CXX=clang++-8

script:
  # - wget https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4.tar.gz
  # - tar -zxvf cmake-3.13.4.tar.gz
  # - cd cmake-3.13.4
  # - ./bootstrap
  # - make
  # - sudo make install
  - $CXX --version
  - ./configure
  - ./build/bin/MlangTest